title: Karneeg Jabourian
email: info@karneegjabourian.coms
description: Experience curator. Listener. Manipulator of sound.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github: [metadata]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
